java -jar VGP-master/dist/VGP.jar ../data-format-parse/amazon_68M.txt.txt_totem 2 -output amazon-2
java -jar VGP-master/dist/VGP.jar ../data-format-parse/RoadNet-CA-79M.txt.txt_totem 2 -output RoadNet
java -jar VGP-master/dist/VGP.jar ../data-format-parse/soc-LiveJournal1.txt.txt_totem 2 -output livejournal
java -jar VGP-master/dist/VGP.jar ../data-format-parse/com-orkut.ungraph.txt.txt_totem 2 -output Orkut
java -jar VGP-master/dist/VGP.jar ../data-format-parse/dblp_88M.txt.txt_totem 2 -output dblp
java -jar VGP-master/dist/VGP.jar ../data-format-parse/web-Stanford.txt.txt_totem 2 -output stanford
java -jar VGP-master/dist/VGP.jar ../data-format-parse/wiki-Talk-59M.txt.txt_totem 2 -output wiki
java -jar VGP-master/dist/VGP.jar ../data-format-parse/youtube_37M.txt.txt_totem 2 -output youtube
java -jar VGP-master/dist/VGP.jar ../data-format-parse/random-graph.txt.txt_totem 2 -output random
java -jar VGP-master/dist/VGP.jar ../data-format-parse/RMAT16_2_2.4G.txt.txt_totem 2 -output RMAT
java -jar VGP-master/dist/VGP.jar ../data-format-parse/twitter_11G.txt.txt_totem 2 -output twitter
java -jar VGP-master/dist/VGP.jar ../data-format-parse/webbase_16G.txt.txt_totem 2 -output webbase